### ISSUE TITLE
Crashes Dedicated Server: 1.16.5-0.7.4.1b

### ISSUE THREAD

**Issue by kreezxil** [Seniorendi/AdvancedPeripherals#220]
### Descripe

I updated to this and now it says can't find the confighandler class on the server.

```
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Progressive Peripherals (progressiveperipherals) has failed to load correctly
§7java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: de/srendi/advancedperipherals/common/configuration/ConfigHandler
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:269) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:236) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:194) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {}
```

### Steps to reproduce

Update to this version, and run it on a dedicated server.

### Multiplayer?

Yes

### Version

0.7.3r (Latest)

### Minecraft, Forge and maybe other related mods versions

36.2.9 1.16.5

### Crashlog/log

https://gist.github.com/a56dd903e2a11baf7e6507b09b873052

**Comment by SirEndii** [comment]
This is actual an issue with Progressive Peripherals. So I will just ping the dev here @SirEdvin 
I pinged him too in discord. So he will eventually answer here.

**Comment by SirEndii** [comment]
To clarify:
You have 3 options now.
— Downgrade AP
— Remove PP(I don't recommend this option)
— Wait until fix

But I know, that you're a good modpack dev. You'll know what's the best for your pack.

**Comment by SirEdvin** [comment]
Oh, I will prepare fix in 1-2 days, sorry for this.

**Comment by kreezxil** [comment]
# 0.7.4r works out of the box tho. :)

**Comment by SirEdvin** [comment]
Hi, @kreezxil  Can you try this version: https://www.curseforge.com/minecraft/mc-mods/progressiveperipherals/files/3528021 please?

**Comment by kreezxil** [comment]
@SirEdvin excellent that version does not crash the server.
