### ISSUE TITLE
Chucky Turtle - Crashes Server

### ISSUE THREAD

**Issue by HelixCreations** [Seniorendi/AdvancedPeripherals#245]
### Description

Minecraft 1.18.1
Forge 39.0.8

Issue - Chunky Turtle crashes the server when the USER leaves the server.

LOG - Does not create a Crash Report

```
[03:16:55] [Server thread/INFO]: **USER** left the game
[03:17:00] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%23117!:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23117!:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23117!:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23117!:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23117!:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.longs.LongArrayList.getLong(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:704) ~[fastutil-8.5.6.jar%2333!:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$FastEntryIterator.next(Long2ObjectOpenHashMap.java:822) ~[fastutil-8.5.6.jar%2333!:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$FastEntryIterator.next(Long2ObjectOpenHashMap.java:816) ~[fastutil-8.5.6.jar%2333!:?]
	at net.minecraft.server.level.DistanceManager.m_140776_(DistanceManager.java:77) ~[server-1.18.1-20211210.034407-srg.jar%23117!:?]
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:308) ~[server-1.18.1-20211210.034407-srg.jar%23117!:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%23117!:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%23117!:?]
	... 5 more
```

### Steps to reproduce

1. Ran Mining Program with Chunky Turtle
2. Disconnected from Server while in same Chunk as Turtle

### Multiplayer?

Yes

### Version

0.7.8r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge 39.0.8

**Comment by SirEndii** [comment]
Does bot look like a issue with AP. I also can't reproduce this.
Try to use only AP with the normal forge server version(No fork like mohist if you use one).
And could you show me your modlist
