### ISSUE TITLE
[Crash] 0.7.11b crash on load

### ISSUE THREAD

**Issue by itsdinkd** [Seniorendi/AdvancedPeripherals#269]
### Descripe

After updating to latest AP, when game loads, it crashes.

```java
[15Feb2022 13:47:53.840] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: File Q:\mc\Instances\Another Quality Modpack 3 [Forge] (1)\mods\advancedperipherals-1.18.1-0.7.11b.jar constructed 0 mods: [], but had 1 mods specified: [advancedperipherals]
[15Feb2022 13:47:54.040] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Failed to initialize mod containers
net.minecraftforge.fml.ModLoadingException: The Mod File Q:\mc\Instances\Another Quality Modpack 3 [Forge] (1)\mods\advancedperipherals-1.18.1-0.7.11b.jar has mods that were not found
	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:255) ~[fmlcore-1.18.1-39.0.66.jar%23381!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:167) ~[fmlcore-1.18.1-39.0.66.jar%23381!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:106) ~[forge-1.18.1-39.0.66-universal.jar%23384!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:127) ~[forge-1.18.1-39.0.66-universal.jar%23384!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:106) ~[forge-1.18.1-39.0.66-universal.jar%23384!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:458) ~[client-1.18.1-20211210.034407-srg.jar%23380!/:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.1-20211210.034407-srg.jar%23380!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.66.jar%2323!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

### Steps to reproduce

update mod and launch game

(your versions in issue template doesn't show the latest)

### Multiplayer?

Yes

### Version

1.18.1-0.7.9r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

39.0.66

**Comment by SirEndii** [comment]
not this again...
but thank you.

**Comment by SirEndii** [comment]
I re-uploaded the jar to curseforge.
This should work now.

**Comment by m-doescode** [comment]
@Seniorendi Hi,

Could you please do the same for the Modrinth page too?

Thanks.

**Comment by SirEndii** [comment]
What do you mean?

You need to use the latest version on modrinth, the old 1.18.1-0.7.11b is not supported anymore

**Comment by m-doescode** [comment]
@Seniorendi 
Excuse me, my fault

I mixed this version up with 0.7.21b, as the same error occurs as the person above mentions. Strangely, this bug only occurs in the modrinth version of the file.

So I assumed the issue was talking about the same version.

Really sorry, have a nice day!
