### ISSUE TITLE
AR Glasses don't display

### ISSUE THREAD

**Issue by BingusManLeftToenail** [Seniorendi/AdvancedPeripherals#358]
### Describe

I took the exact code off the wiki
`local controller = peripheral.find("arController") -- Finds the peripheral if one is connected

if controller == nil then error("arController not found") end

controller.setRelativeMode(true, 1600, 900) -- Convenient Aspect ratio for most screens
while true do
  local timer = os.startTimer(1)
  local event, id
  repeat
    event, id = os.pullEvent("timer")
  until id == timer
  controller.clear() -- If you don't do this, the texts will draw over each other
  controller.drawRightboundString(os.date(), -10, 10, 0xffffff)
end`

Linked the glasses, and nothing is displaying. I thought at first it was optifine, but I removed that and still naughta. 

### Steps to reproduce

1. Computer
2. AR Controller to the left of the computer or hooked via wired modem
3. AR Glasses link
4. Put them bad bois on
5. Run that program
6. Crickets

### Multiplayer?

Yes

### Version

1.18.2-0.7.19r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.52 (Whatever the minimum was for the req of the mod)

**Comment by BingusManLeftToenail** [comment]
I also had just tried clearing the glasses and drawing a string with no results.

**Comment by SirEndii** [comment]
the example code from the website is a bit broken
And it seems that the relative mode does not work.

You can try to change the coords of the string, like instead of `-10` something like `50`

the ar system is buggy and bad currently, sorry for that

**Comment by BingusManLeftToenail** [comment]
Its all good. Thank you for workin on it :)

**Comment by BingusManLeftToenail** [comment]
[10:44:18] [Server thread/ERROR] [minecraft/BlockEntity]: Failed to load data for block entity advancedperipherals:ar_controller
java.lang.IllegalArgumentException: No enum constant de.srendi.advancedperipherals.common.argoggles.RenderActionType.DrawRightboundString
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at de.srendi.advancedperipherals.common.argoggles.RenderActionType.valueOf(RenderActionType.java:5) ~[AdvancedPeripherals-0.7.19r.jar%2338!/:0.7.19r]
	at de.srendi.advancedperipherals.common.argoggles.ARRenderAction.deserializeNBT(ARRenderAction.java:142) ~[AdvancedPeripherals-0.7.19r.jar%2338!/:0.7.19r]
	at de.srendi.advancedperipherals.common.blocks.blockentities.ARControllerEntity.deserializeNBT(ARControllerEntity.java:77) ~[AdvancedPeripherals-0.7.19r.jar%2338!/:0.7.19r]
	at de.srendi.advancedperipherals.common.blocks.blockentities.ARControllerEntity.m_142466_(ARControllerEntity.java:65) ~[AdvancedPeripherals-0.7.19r.jar%2338!/:0.7.19r]
	at net.minecraft.world.level.block.entity.BlockEntity.m_155246_(BlockEntity.java:122) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.level.block.entity.BlockEntity.m_155241_(BlockEntity.java:120) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_196900_(ChunkSerializer.java:412) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:417) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.level.ChunkMap.m_202988_(ChunkMap.java:659) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at net.minecraft.server.level.ChunkMap.m_202985_(ChunkMap.java:643) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:532) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:540) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:129) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.level.Level.m_6522_(Level.java:169) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:123) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.level.Level.m_6325_(Level.java:164) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.level.Level.m_46745_(Level.java:160) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.level.Level.m_6425_(Level.java:398) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.entity.Entity.m_20323_(Entity.java:1104) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.entity.Entity.m_6075_(Entity.java:438) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:321) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:413) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2215) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2344!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[10:44:18] [Server thread/WARN] [minecraft/BlockEntity]: Skipping BlockEntity with id advancedperipherals:ar_controller

Im not sure if this has anything to do with it?

**Comment by SirEndii** [comment]
this is a weird issue
breaking the block should fix it

**Comment by BingusManLeftToenail** [comment]
I'm having issues even getting my game to run right now (Not your mod's fault, optifine being.. Optifine.) I got the AR glasses to work with what you suggested. Thank you! :D

**Comment by BingusManLeftToenail** [comment]
And to clear any confusion, I was running tests without optifine installed to see if it was that causing the issue. Because I know that's a common cause

**Comment by SirEndii** [comment]
I will close this now since in favor of the smart glasses
They will also come to 1.18.2
