### ISSUE TITLE
`rsBridge.listItems()` `Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER``

### ISSUE THREAD

**Issue by Quezler** [Seniorendi/AdvancedPeripherals#370]
### Describe

![Screenshot 2022-11-27 at 13 00 56](https://user-images.githubusercontent.com/3179271/204134130-019b6a8f-f35b-4bf3-93e7-009753f3cd3b.png)

```
[12:00:04] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[12:00:04] [Server thread/ERROR] [computercraft/]: Error running task
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
        at mod.chiselsandbits.item.MagnifyingGlassItem.m_7626_(MagnifyingGlassItem.java:33) ~[ChiselsBits-forge-1.18.2-1.2.114-universal.jar%2371!/:1.2.114] {re:classloading,pl:epic_rei_lmao:B}
        at net.minecraft.world.item.ItemStack.m_41786_(ItemStack.java:593) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:itemstack,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:ae2wtlib.mixins.json:Restock,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:A}
        at net.minecraft.world.item.ItemStack.m_41611_(ItemStack.java:929) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:itemstack,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:ae2wtlib.mixins.json:Restock,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:A}
        at de.srendi.advancedperipherals.common.addons.refinedstorage.RefinedStorage.getFingerpint(RefinedStorage.java:256) ~[AdvancedPeripherals-0.7.20r.jar%2341!/:0.7.20r] {re:classloading,pl:epic_rei_lmao:B}
        at de.srendi.advancedperipherals.common.addons.refinedstorage.RefinedStorage.getObjectFromStack(RefinedStorage.java:155) ~[AdvancedPeripherals-0.7.20r.jar%2341!/:0.7.20r] {re:classloading,pl:epic_rei_lmao:B}
        at de.srendi.advancedperipherals.common.addons.refinedstorage.RefinedStorage.lambda$listItems$1(RefinedStorage.java:59) ~[AdvancedPeripherals-0.7.20r.jar%2341!/:0.7.20r] {re:classloading,pl:epic_rei_lmao:B}
        at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {re:mixin}
        at de.srendi.advancedperipherals.common.addons.refinedstorage.RefinedStorage.listItems(RefinedStorage.java:59) ~[AdvancedPeripherals-0.7.20r.jar%2341!/:0.7.20r] {re:classloading,pl:epic_rei_lmao:B}
        at de.srendi.advancedperipherals.common.addons.computercraft.peripheral.RsBridgePeripheral.lambda$listItems$0(RsBridgePeripheral.java:74) ~[AdvancedPeripherals-0.7.20r.jar%2341!/:0.7.20r] {re:classloading,pl:epic_rei_lmao:B}
        at de.srendi.advancedperipherals.common.addons.computercraft.peripheral.RsBridgePeripheral.ensureIsConnected(RsBridgePeripheral.java:59) ~[AdvancedPeripherals-0.7.20r.jar%2341!/:0.7.20r] {re:classloading,pl:epic_rei_lmao:B}
        at de.srendi.advancedperipherals.common.addons.computercraft.peripheral.RsBridgePeripheral.listItems(RsBridgePeripheral.java:74) ~[AdvancedPeripherals-0.7.20r.jar%2341!/:0.7.20r] {re:classloading,pl:epic_rei_lmao:B}
        at de.srendi.advancedperipherals.common.addons.computercraft.peripheral.RsBridgePeripheral$cc$listItems117.apply(CC generated method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at dan200.computercraft.core.asm.PeripheralMethod.lambda$static$0(PeripheralMethod.java:21) ~[cc-tweaked-1.18.2-1.101.0.jar%2364!/:1.101.0] {re:classloading,pl:epic_rei_lmao:B}
        at dan200.computercraft.core.computer.LuaContext.lambda$issueMainThreadTask$0(LuaContext.java:32) ~[cc-tweaked-1.18.2-1.101.0.jar%2364!/:1.101.0] {re:classloading,pl:epic_rei_lmao:B}
        at dan200.computercraft.core.computer.mainthread.MainThreadExecutor.execute(MainThreadExecutor.java:146) ~[cc-tweaked-1.18.2-1.101.0.jar%2364!/:1.101.0] {re:classloading,pl:epic_rei_lmao:B}
        at dan200.computercraft.core.computer.mainthread.MainThread.tick(MainThread.java:144) ~[cc-tweaked-1.18.2-1.101.0.jar%2364!/:1.101.0] {re:classloading,pl:epic_rei_lmao:B}
        at dan200.computercraft.shared.computer.core.ServerContext.tick(ServerContext.java:148) ~[cc-tweaked-1.18.2-1.101.0.jar%2364!/:1.101.0] {re:classloading,pl:epic_rei_lmao:B}
        at dan200.computercraft.shared.CommonHooks.onServerTick(CommonHooks.java:55) ~[cc-tweaked-1.18.2-1.101.0.jar%2364!/:1.101.0] {re:classloading,pl:epic_rei_lmao:B}
        at net.minecraftforge.eventbus.ASMEventHandler_457_CommonHooks_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:937) ~[forge-1.18.2-40.1.84-universal.jar%23259!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:840) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Unknown Source) [?:?] {}
```

### Steps to reproduce

Have this in your drives while trying to list the items:
![Screenshot 2022-11-27 at 13 03 01](https://user-images.githubusercontent.com/3179271/204134200-01db567d-e483-481d-a85b-b3e0d46baf3e.png)

### Multiplayer?

Yes

### Version

1.18.2-0.7.20r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

FTB Stoneblock 3 1.3.0

**Comment by SirEndii** [comment]
Please report the error to chisel and bits, we don't use the Minecraft class for this use case
