### ISSUE TITLE
RS Bridge getPattern function fails on Stoneblocks 3 Modpack [MC 1.18.2]

### ISSUE THREAD

**Issue by ritterdaniel** [Seniorendi/AdvancedPeripherals#394]
### Describe

I created and stored a RS Pattern for the "Ultimate Stew" item.
Whenever I try to call the RS Bridge getPattern function a ClassCastException occurs.
In addition I  tested it with other RS pattern but it fails for all of them.

### Steps to reproduce

1. Install Modpack Stoneblocks 3
2. Create RS system with a RS bridge, a computer and a wired modem
3. Create and store a Pattern for an item ( I used the Ultimate Stew item)
4. Execute the following code
```
rs  = peripheral("rsBridge_0")
local ustew = rs.getPattern({name = "avaritia:ultimate_stew"})
```

### Multiplayer?

Yes

### Version

1.18.2-0.7.21r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.92 Minecraft 1.18.2 CC: Tweaked 1.101.0

### Screenshots or Videos

https://drive.google.com/file/d/1L9maFtW1xHIbDV5BKd_hpbHVkxbEjYjb/view?usp=share_link
https://drive.google.com/file/d/1gYqZLsaTmFw90svY5Cr_sOIzwfZ2C23y/view?usp=share_link
https://drive.google.com/file/d/1J8nPzskBj6Lx5A4E9x44QOsVvDduMQ-B/view?usp=share_link

### Crashlog/log

```
[16:14:05] [Server thread/ERROR] [computercraft/]: Error running task
java.lang.ClassCastException: class java.util.HashMap cannot be cast to class dan200.computercraft.api.lua.MethodResult (java.util.HashMap is in module java.base of loader 'bootstrap'; dan20
0.computercraft.api.lua.MethodResult is in module computercraft@1.101.0 of loader 'TRANSFORMER' @26d5a317)
        at de.srendi.advancedperipherals.common.addons.computercraft.peripheral.RsBridgePeripheral.getPattern(RsBridgePeripheral.java:138) ~[AdvancedPeripherals-0.7.21r.jar%2341!/:0.7.21r] {re:classloading,pl:rei_plugin_compatibilities:B}
        at de.srendi.advancedperipherals.common.addons.computercraft.peripheral.RsBridgePeripheral$cc$getPattern135.apply(CC generated method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at dan200.computercraft.core.asm.PeripheralMethod.lambda$static$0(PeripheralMethod.java:21) ~[cc-tweaked-1.18.2-1.101.0.jar%2365!/:1.101.0] {re:classloading,pl:rei_plugin_compatibilities:B}
        at dan200.computercraft.core.computer.LuaContext.lambda$issueMainThreadTask$0(LuaContext.java:32) ~[cc-tweaked-1.18.2-1.101.0.jar%2365!/:1.101.0] {re:classloading,pl:rei_plugin_compatibilities:B}
        at dan200.computercraft.core.computer.mainthread.MainThreadExecutor.execute(MainThreadExecutor.java:146) ~[cc-tweaked-1.18.2-1.101.0.jar%2365!/:1.101.0] {re:classloading,pl:rei_plugin_compatibilities:B}
        at dan200.computercraft.core.computer.mainthread.MainThread.tick(MainThread.java:144) ~[cc-tweaked-1.18.2-1.101.0.jar%2365!/:1.101.0] {re:classloading,pl:rei_plugin_compatibilities:B}
        at dan200.computercraft.shared.computer.core.ServerContext.tick(ServerContext.java:148) ~[cc-tweaked-1.18.2-1.101.0.jar%2365!/:1.101.0] {re:classloading,pl:rei_plugin_compatibilities:B}
        at dan200.computercraft.shared.CommonHooks.onServerTick(CommonHooks.java:55) ~[cc-tweaked-1.18.2-1.101.0.jar%2365!/:1.101.0] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraftforge.eventbus.ASMEventHandler_460_CommonHooks_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:937) ~[forge-1.18.2-40.1.92-universal.jar%23265!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:840) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Unknown Source) [?:?] {}
```

**Comment by SirEndii** [comment]
Fixed a while ago but not published
https://github.com/SirEndii/AdvancedPeripherals/commit/8b4940e89c2248e44c6818029fcddf03a2770b6c
