### ISSUE TITLE
1.20.1 broken Patchouli book

### ISSUE THREAD

**Issue by gardenappl** [Seniorendi/AdvancedPeripherals#511]
### Describe

```
[10вер.2023 13:25:29.609] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book advancedperipherals:manual defined by mod advancedperipherals, skipping
java.lang.IllegalArgumentException: Book advancedperipherals:manual has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
        at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:76) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at vazkii.patchouli.forge.common.__ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.20.1-47.1.3.jar%23693!/:?]
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[fmlcore-1.20.1-47.1.3.jar%23692!/:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```

### Steps to reproduce

Launch Minecraft (client or server), book does not work.

### Multiplayer?

Yes

### Version

1.20.1-0.7.32b (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge 47.1.3, Minecraft 1.20.1, Patchouli 1.20.1-81

**Comment by SirEndii** [comment]
The book does work now. However...

![image](https://github.com/SirEndii/AdvancedPeripherals/assets/67484093/24d3d99a-404b-40be-aa0b-af56e6ad1c2e)


I noticed that too late. I'll fix this in the next days or maybe remove that book entirely

**Comment by SirEndii** [comment]
False alarm. It was an issue with my local dev environment.
